version: '3.3'

networks:
  flask_rede:
    driver: bridge

services:
  conversao-distancia:
    image: franciscofrancod/conversao-distancia:v1
    restart: always
    networks:
      - flask_rede
    ports:
      - 5000:5000
    